"use client"



export default function RootLayout({ children }) {
 return (
   <html lang="en">
     <body>
       
       {children}
     </body>
     <div class="overlay"></div>
    </html>
  )
}


// export const metadata = {
//   title: 'CS Notes',
//   description: 'Generated by Next.js',
// }

// {/* <AppContext>
//          <Provider store={store}>
//           {children}
//          </Provider>
//        </AppContext> */}
//        {/* <Provider store={store}>
//           {children}
//        </Provider> */}
